require 'config.settings'.setopts('g', {
  { 'neovide_opacity',                       1 },
  { 'neovide_floating_blur_amount_x',        2.0 },
  { 'neovide_floating_blur_amount_y',        2.0 },
  { 'neovide_floating_shadow',               true },
  { 'neovide_floating_z_height',             10 },
  { 'neovide_light_angle_degrees',           45 },
  { 'neovide_light_radius',                  5 },
  { 'neovide_hide_mouse_when_typing',        true },
  { 'neovide_cursor_animate_in_insert_mode', false },
  { 'neovide_cursor_vfx_mode',               'railgun' },
  { 'neovide_cursor_vfx_particle_density',   10.0 },
  { 'neovide_scroll_animation_far_lines',    0 },
  { 'neovide_scroll_animation_length',       0.2 },
})
